using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <summary>
    /// Stub for a migration that was briefly deployed then removed from source.
    /// Keeps __EFMigrationsHistory compatible; table creation is handled by later migrations.
    /// </summary>
    [Migration( "20260718181444_AddKirmaBukinistkaOffers" )]
    public partial class AddKirmaBukinistkaOffersLegacy : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaOffers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ShopifyProductId" character varying(64) NOT NULL,
                    "ShopifyVariantId" character varying(64) NOT NULL,
                    "ProductName" character varying(512) NOT NULL,
                    "ProductAuthor" character varying(256) NOT NULL,
                    "MainImageUrl" character varying(2048) NULL,
                    "ProductAdminUrl" character varying(2048) NOT NULL,
                    "StorefrontUrl" character varying(2048) NOT NULL,
                    "SupplierName" character varying(256) NULL,
                    "Quantity" integer NOT NULL,
                    "GrossUnitCost" numeric(18,2) NOT NULL,
                    "CreatedByLogin" character varying(256) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_KirmaBukinistkaOffers" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_KirmaBukinistkaOffers_CreatedAtUtc"
                    ON "KirmaBukinistkaOffers" ("CreatedAtUtc");
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql( @"DROP TABLE IF EXISTS ""KirmaBukinistkaOffers"";" );
        }
    }
}
