using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [Migration( "20260722163000_AddKirmaBukinistkaPosSales" )]
    public class AddKirmaBukinistkaPosSales : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaPosSales" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "OdooPosOrderId" integer NOT NULL,
                    "OdooPosOrderLineId" integer NOT NULL,
                    "OdooPosOrderName" character varying(128) NULL,
                    "OfferId" integer NULL,
                    "OdooProductId" integer NOT NULL,
                    "ShopifyProductId" character varying(64) NOT NULL,
                    "ShopifyVariantId" character varying(64) NOT NULL DEFAULT '',
                    "Quantity" integer NOT NULL,
                    "ProductName" character varying(512) NOT NULL,
                    "IsOwnStock" boolean NOT NULL DEFAULT false,
                    "SoldAtUtc" timestamp with time zone NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_KirmaBukinistkaPosSales" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_Line_Offer"
                    ON "KirmaBukinistkaPosSales" ("OdooPosOrderLineId", "OfferId")
                    WHERE "OfferId" IS NOT NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_Line_Own"
                    ON "KirmaBukinistkaPosSales" ("OdooPosOrderLineId")
                    WHERE "IsOwnStock" = true;
                CREATE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_SoldAtUtc"
                    ON "KirmaBukinistkaPosSales" ("SoldAtUtc");
                CREATE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_OdooProductId"
                    ON "KirmaBukinistkaPosSales" ("OdooProductId");

                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaPosSyncStates" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LastSyncedAtUtc" timestamp with time zone NULL,
                    "LastProcessedOrderId" integer NULL,
                    CONSTRAINT "PK_KirmaBukinistkaPosSyncStates" PRIMARY KEY ("Id")
                );
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "KirmaBukinistkaPosSales";
                DROP TABLE IF EXISTS "KirmaBukinistkaPosSyncStates";
                """ );
        }
    }
}
