using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [Migration( "20260722170000_AddBukinistkaOwnStockBuffer" )]
    public class AddBukinistkaOwnStockBuffer : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "KirmaBukinistkaPosSales"
                    ADD COLUMN IF NOT EXISTS "IsOwnStock" boolean NOT NULL DEFAULT false;

                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaOdooOwnStockBuffers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "OdooProductId" integer NOT NULL,
                    "OwnQtyRemaining" integer NOT NULL DEFAULT 0,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_KirmaBukinistkaOdooOwnStockBuffers" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaOdooOwnStockBuffers_OdooProductId"
                    ON "KirmaBukinistkaOdooOwnStockBuffers" ("OdooProductId");

                -- Replace non-partial unique index if an older deploy created it.
                DROP INDEX IF EXISTS "IX_KirmaBukinistkaPosSales_Line_Offer";
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_Line_Offer"
                    ON "KirmaBukinistkaPosSales" ("OdooPosOrderLineId", "OfferId")
                    WHERE "OfferId" IS NOT NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaPosSales_Line_Own"
                    ON "KirmaBukinistkaPosSales" ("OdooPosOrderLineId")
                    WHERE "IsOwnStock" = true;
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "KirmaBukinistkaOdooOwnStockBuffers";
                ALTER TABLE "KirmaBukinistkaPosSales" DROP COLUMN IF EXISTS "IsOwnStock";
                """ );
        }
    }
}
