using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [Migration( "20260722180000_AddBukinistkaSyncOnSaleAndShopifyDelivery" )]
    public class AddBukinistkaSyncOnSaleAndShopifyDelivery : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "KirmaBukinistkaOffers"
                    ADD COLUMN IF NOT EXISTS "SyncOnSale" boolean NOT NULL DEFAULT false;

                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaShopifyDeliverySyncs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ShopifyOrderId" character varying(64) NOT NULL,
                    "ShopifyOrderNumber" character varying(64) NOT NULL,
                    "ShopifyProductId" character varying(64) NOT NULL,
                    "ShopifyVariantId" character varying(64) NOT NULL DEFAULT '',
                    "OfferId" integer NOT NULL,
                    "OdooProductId" integer NOT NULL,
                    "Quantity" integer NOT NULL,
                    "OdooPickingId" integer NOT NULL,
                    "OdooPickingName" character varying(128) NULL,
                    "SoldAtUtc" timestamp with time zone NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_KirmaBukinistkaShopifyDeliverySyncs" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaShopifyDeliverySyncs_Order_Product_Offer"
                    ON "KirmaBukinistkaShopifyDeliverySyncs" ("ShopifyOrderId", "ShopifyProductId", "ShopifyVariantId", "OfferId");
                CREATE INDEX IF NOT EXISTS "IX_KirmaBukinistkaShopifyDeliverySyncs_SoldAtUtc"
                    ON "KirmaBukinistkaShopifyDeliverySyncs" ("SoldAtUtc");

                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaShopifyDeliverySyncStates" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LastSyncedAtUtc" timestamp with time zone NULL,
                    CONSTRAINT "PK_KirmaBukinistkaShopifyDeliverySyncStates" PRIMARY KEY ("Id")
                );
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "KirmaBukinistkaShopifyDeliverySyncs";
                DROP TABLE IF EXISTS "KirmaBukinistkaShopifyDeliverySyncStates";
                ALTER TABLE "KirmaBukinistkaOffers" DROP COLUMN IF EXISTS "SyncOnSale";
                """ );
        }
    }
}
