using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [Migration( "20260727210000_AddKirmaBukinistkaReceiptDrafts" )]
    public class AddKirmaBukinistkaReceiptDrafts : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaReceiptDrafts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Status" character varying(32) NOT NULL,
                    "CreatedByLogin" character varying(256) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL,
                    "LastError" character varying(2048) NULL,
                    "OdooPickingId" integer NULL,
                    "OdooPickingName" character varying(128) NULL,
                    CONSTRAINT "PK_KirmaBukinistkaReceiptDrafts" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_KirmaBukinistkaReceiptDrafts_Status"
                    ON "KirmaBukinistkaReceiptDrafts" ("Status");

                CREATE TABLE IF NOT EXISTS "KirmaBukinistkaReceiptDraftLines" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ReceiptDraftId" integer NOT NULL,
                    "OfferId" integer NOT NULL,
                    "OdooProductId" integer NOT NULL,
                    "OdooProductName" character varying(512) NOT NULL,
                    "ListPrice" numeric(18,2) NULL,
                    "ApplyKirmaCostPrice" boolean NULL,
                    CONSTRAINT "PK_KirmaBukinistkaReceiptDraftLines" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_KirmaBukinistkaReceiptDraftLines_Drafts"
                        FOREIGN KEY ("ReceiptDraftId")
                        REFERENCES "KirmaBukinistkaReceiptDrafts" ("Id")
                        ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_KirmaBukinistkaReceiptDraftLines_Draft_Offer"
                    ON "KirmaBukinistkaReceiptDraftLines" ("ReceiptDraftId", "OfferId");
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "KirmaBukinistkaReceiptDraftLines";
                DROP TABLE IF EXISTS "KirmaBukinistkaReceiptDrafts";
                """ );
        }
    }
}
