using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [Migration( "20260910230000_AddKirmashes" )]
    public class AddKirmashes : Migration
    {
        protected override void Up( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Kirmashes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Title" character varying(256) NOT NULL,
                    "Description" text NOT NULL DEFAULT '',
                    "EventDate" date NOT NULL,
                    "Status" character varying(32) NOT NULL DEFAULT 'draft',
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Kirmashes" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "KirmashLines" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KirmashId" integer NOT NULL,
                    "ShopifyProductId" character varying(64) NOT NULL,
                    "ShopifyVariantId" character varying(64) NOT NULL DEFAULT '',
                    "Title" character varying(512) NOT NULL,
                    "UnitPrice" numeric(12,2) NOT NULL,
                    "Quantity" integer NOT NULL,
                    CONSTRAINT "PK_KirmashLines" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_KirmashLines_Kirmashes"
                        FOREIGN KEY ("KirmashId") REFERENCES "Kirmashes" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_KirmashLines_KirmashId"
                    ON "KirmashLines" ("KirmashId");

                CREATE TABLE IF NOT EXISTS "KirmashPriceTags" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KirmashId" integer NOT NULL,
                    "KirmashLineId" integer NOT NULL,
                    "Sequence" integer NOT NULL,
                    "Title" character varying(512) NOT NULL,
                    "UnitPrice" numeric(12,2) NOT NULL,
                    "CheckoutUrl" character varying(2048) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_KirmashPriceTags" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_KirmashPriceTags_Kirmashes"
                        FOREIGN KEY ("KirmashId") REFERENCES "Kirmashes" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_KirmashPriceTags_KirmashLines"
                        FOREIGN KEY ("KirmashLineId") REFERENCES "KirmashLines" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_KirmashPriceTags_KirmashId"
                    ON "KirmashPriceTags" ("KirmashId");
                CREATE INDEX IF NOT EXISTS "IX_KirmashPriceTags_KirmashLineId"
                    ON "KirmashPriceTags" ("KirmashLineId");
                """ );
        }

        protected override void Down( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "KirmashPriceTags";
                DROP TABLE IF EXISTS "KirmashLines";
                DROP TABLE IF EXISTS "Kirmashes";
                """ );
        }
    }
}
