using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    public partial class AddShopifyShopCredentials : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ShopifyShopCredentials" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Shop" character varying(256) NOT NULL,
                    "AccessToken" character varying(512) NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_ShopifyShopCredentials" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShopifyShopCredentials_Shop"
                    ON "ShopifyShopCredentials" ("Shop");
                """ );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql( @"DROP TABLE IF EXISTS ""ShopifyShopCredentials"";" );
        }
    }
}
